### ISSUE TITLE
default scope

### ISSUE THREAD

**Issue by nabeta** [datacite/omniauth-orcid#2]
I'm using omniauth-orcid-1.0.30.
According to CHANGELOG, the default scope is changed to "/authenticate" in 1.0. But it was reverted in 
https://github.com/datacite/omniauth-orcid/commit/e28a931d1bb02ad39a9f03ce95143c7401c5a8ec . Is it an intended change?

**Comment by mfenner** [comment]
It was a temporary change, it will be `/authenticate` in 1.1, as my guess is that the majority of users of the gem are not ORCID members.

**Comment by mfenner** [comment]
Default scope depends on the `member` option since the 1.2 release. If `member` is not set, the default scope is `/authenticate`. The default scope for `member: true` is `/read-limited /activities/update /orcid-bio/update`.
