### ISSUE TITLE
Support omniauth-oauth2 1.4.0

### ISSUE THREAD

**Issue by yob** [datacite/omniauth-orcid#6]
I can see that in #1, this gem was changed to require `omniauth-oauth2` 1.3.1.

Since the breaking change in `omniauth-oauth2` 1.4.0 was released, it seems the `omniauth-facebook` and `omniauth-google-oauth2` gems have released updates that continue to work.

The [fix for omniauth-facebook](https://github.com/mkdynamic/omniauth-facebook/pull/221) looks like it wasn't too complicated - is there any chance the fix for this gem will be as simple?

**Comment by mfenner** [comment]
See pull request #7 that I just merged. Will do a new release with the changes soon, until then use the master branch.

**Comment by yob** [comment]
Thanks!

**Comment by yob** [comment]
Hi - just checking in on this. Are there any plans for a new release?

**Comment by mfenner** [comment]
`omniauth-oauth2` 1.4.0 is now supported in `omniauth-orcid` 1.2.x.
